'''
This script will copy the certs generated by certbot to the foundry directories
'''

shopt -s nullglob

dirs=$(ls -d /home/dtickell/foundry*)
array=( $dirs )


for i in "${array[@]}"
do
        echo "Copying Certs to $i"
        sudo cp /etc/letsencrypt/live/foundry.tnbk00.com/fullchain.pem $i/foundrydata/Config/fullchain.pem
        sudo cp /etc/letsencrypt/live/foundry.tnbk00.com/privkey.pem $i/foundrydata/Config/privkey.pem
        echo "Done with $i"
done
